FROM registry.cn-hangzhou.aliyuncs.com/choerodon-tools/javabase:0.8.0
COPY app.jar /asgard-service.jar
COPY dist /dist
COPY enterpoint.sh /enterpoint.sh
CMD ["sh", "/enterpoint.sh", "java", "$JAVA_OPTS", "$SKYWALKING_OPTS" "-jar" "/asgard-service.jar"]